{% set name = "distlib" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: d982d0751ff6eaaab5e2ec8e691d949ee80eddf01a62eaa96ddb11531fe16b05

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 2.7|>=3.6
    - setuptools
    - wheel
  run:
    - python 2.7|>=3.6

test:
  imports:
    - distlib
    - distlib._backport
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/distlib/
  summary: Distribution utilities
  dev_url: https://bitbucket.org/pypa/distlib/
  doc_url: https://distlib.readthedocs.io/en/latest/
  license: Python Software Foundation License
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nicoddemus
