{% set name = "distlib" %}
{% set version = "0.3.6" %}
{% set checksum = "14bad2d9b04d3a36127ac97f30b12a19268f211063d8f8ee4f47108896e11b46" %}
{% set build = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [not (py27 or py>36)]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - distlib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/distlib/
  summary: Distribution utilities for python
  description: |
    A library which implements low-level functions that relate to packaging and distribution of python.
  dev_url: https://github.com/pypa/distlib
  doc_url: https://distlib.readthedocs.io/
  license: Python-2.0
  license_family: PSF
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nicoddemus
