{% set name = "distlib" %}
{% set version = "0.4.0" %}
{% set checksum = "feec40075be03a04501a973d81f633735b4b69f98b05450592310c0f401a4e0d" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [not (py27 or py>36)]

requirements:
  host:
    - pip
    - python
    - setuptools >=44
    - wheel >=0.29.0
  run:
    - python
  build:
    - {{ compiler('c') }}

test:
  imports:
    - distlib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/distlib/
  summary: Distribution utilities for python
  description: |
    A library which implements low-level functions that relate to packaging and distribution of python.
  dev_url: https://github.com/pypa/distlib
  doc_url: https://distlib.readthedocs.io/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nicoddemus
