{% set name = "distlib" %}
{% set version = "0.3.8" %}
{% set checksum = "1530ea13e350031b6312d8580ddb6b27a104275a31106523b8f123787f494f64" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: True  # [not (py27 or py>36)]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - distlib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/distlib/
  summary: Distribution utilities for python
  description: |
    A library which implements low-level functions that relate to packaging and distribution of python.
  dev_url: https://github.com/pypa/distlib
  doc_url: https://distlib.readthedocs.io/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nicoddemus
